// AUTO-GENERATED by scripts/convert-chapters.js — do not edit manually
export const sections = [
  {
    id: 'version-overview',
    title: 'Java Version Overview (9-26)',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java Version Overview (9-26)</h2>
      <p class="note"><strong>LTS (Long-Term Support):</strong> Java 8, 11, 17, 21, 25 receive extended support for 5-8 years. Non-LTS versions get 6 months support.</p>
      <table class="version-table">
        <tr>
          <th>Version</th>
          <th>Release Year</th>
          <th>LTS?</th>
          <th>Key Features</th>
        </tr>
        <tr>
          <td><span class="badge">Java 9</span></td>
          <td>2017</td>
          <td>—</td>
          <td>JPMS (modules), Collection factories, Stream improvements, JShell</td>
        </tr>
        <tr>
          <td><span class="badge">Java 10</span></td>
          <td>2018</td>
          <td>—</td>
          <td>var keyword, unmodifiable copies</td>
        </tr>
        <tr>
          <td><span class="badge lts">Java 11</span></td>
          <td>2018</td>
          <td>✓ LTS</td>
          <td>String.strip(), Files I/O, HttpClient, single-file programs</td>
        </tr>
        <tr>
          <td><span class="badge">Java 12</span></td>
          <td>2019</td>
          <td>—</td>
          <td>Switch expressions (preview), String.indent()</td>
        </tr>
        <tr>
          <td><span class="badge">Java 13</span></td>
          <td>2019</td>
          <td>—</td>
          <td>Text blocks (preview)</td>
        </tr>
        <tr>
          <td><span class="badge">Java 14</span></td>
          <td>2020</td>
          <td>—</td>
          <td>Records (preview), instanceof patterns (preview), better NPE messages</td>
        </tr>
        <tr>
          <td><span class="badge">Java 15</span></td>
          <td>2020</td>
          <td>—</td>
          <td>Text blocks (final), sealed classes (preview), String.formatted()</td>
        </tr>
        <tr>
          <td><span class="badge">Java 16</span></td>
          <td>2021</td>
          <td>—</td>
          <td>Records (final), instanceof patterns (final), Stream.toList(), mapMulti()</td>
        </tr>
        <tr>
          <td><span class="badge lts">Java 17</span></td>
          <td>2021</td>
          <td>✓ LTS</td>
          <td>Sealed classes (final), pattern matching switch (preview), RandomGenerator</td>
        </tr>
        <tr>
          <td><span class="badge">Java 18</span></td>
          <td>2022</td>
          <td>—</td>
          <td>Virtual Threads (preview), jwebserver, UTF-8 default</td>
        </tr>
        <tr>
          <td><span class="badge">Java 19</span></td>
          <td>2022</td>
          <td>—</td>
          <td>Virtual Threads (preview v2), structured concurrency (preview)</td>
        </tr>
        <tr>
          <td><span class="badge">Java 20</span></td>
          <td>2023</td>
          <td>—</td>
          <td>Virtual Threads (preview v3), record patterns (preview)</td>
        </tr>
        <tr>
          <td><span class="badge lts">Java 21</span></td>
          <td>2023</td>
          <td>✓ LTS</td>
          <td>Virtual Threads (final), record patterns (final), sequenced collections</td>
        </tr>
        <tr>
          <td><span class="badge">Java 22</span></td>
          <td>2024</td>
          <td>—</td>
          <td>Unnamed variables (_), unnamed classes (preview), FFM API (final)</td>
        </tr>
        <tr>
          <td><span class="badge">Java 23</span></td>
          <td>2024</td>
          <td>—</td>
          <td>Primitive patterns in switch, Markdown in Javadoc</td>
        </tr>
        <tr>
          <td><span class="badge">Java 24</span></td>
          <td>2025</td>
          <td>—</td>
          <td>Stream.gather() (final), class-file API (final)</td>
        </tr>
        <tr>
          <td><span class="badge lts">Java 25</span></td>
          <td>2025</td>
          <td>✓ LTS</td>
          <td>Unnamed classes final, flexible constructor bodies, module imports</td>
        </tr>
        <tr>
          <td><span class="badge">Java 26</span></td>
          <td>2026</td>
          <td>—</td>
          <td>Value classes (preview), scoped values (final), more pattern matching</td>
        </tr>
      </table>` }} />
    ),
  },
  {
    id: 'java9',
    title: 'Java 9 (2017): JPMS, Collections, Streams',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 9 (2017): JPMS, Collections, Streams</h2>

      <h3>1. Java Platform Module System (JPMS)</h3>
      <p class="important"><strong>What it is:</strong> Explicit module declarations, strong encapsulation, dependencies, service loading. Every module declares what it needs and what it exports.</p>

      <h4>Module Declaration Syntax</h4>
      <pre><code class="language-java">// File: src/module-info.java (at source root, parallel to packages)
module com.myapp {
    // REQUIRES: dependencies on other modules
    requires java.sql;                    // standard module
    requires transitive java.xml;         // transitive: users of myapp get xml too
    requires static java.logging;         // optional (compile-time only)

    // EXPORTS: packages visible outside this module
    exports com.myapp.api;                // only this package is public
    exports com.myapp.util to com.other;  // qualified export

    // OPENS: allow reflection (for frameworks like Jackson, Spring)
    opens com.myapp.model;                // reflection on entire package
    opens com.myapp.config to
        com.fasterxml.jackson.databind;   // qualified open

    // USES & PROVIDES: service discovery pattern
    uses com.myapp.spi.Plugin;            // this module uses Plugin

    provides com.myapp.spi.Plugin
        with com.myapp.impl.DefaultPlugin,  // can provide multiple impls
                com.myapp.impl.AdvancedPlugin;
}</code></pre>

      <h4>Module Diagram</h4>
      <pre class="diagram">
java.base (always implicitly required)
    │
    ├── java.sql
    │   ├── JDBC drivers
    │   └── Connection, Statement, etc
    │
    ├── java.xml
    │   ├── SAX, DOM, StAX parsing
    │   └── (transitive from com.myapp)
    │
    └── com.myapp (our module)
        ├── exports com.myapp.api
        ├── opens   com.myapp.model
        └── uses    com.myapp.spi.Plugin
            │
            ├─→ provides com.myapp.impl.DefaultPlugin
            └─→ provides com.myapp.impl.AdvancedPlugin
      </pre>

      <h4>Service Discovery Example</h4>
      <pre><code class="language-java">// File: com/myapp/spi/Plugin.java
public interface Plugin {
    String getName();
    void execute();
}

// File: com/myapp/impl/DefaultPlugin.java (in same module or different)
public class DefaultPlugin implements Plugin {
    @Override
    public String getName() { return "Default"; }
    @Override
    public void execute() { System.out.println("Executing default"); }
}

// File: com/myapp/App.java (consumer)
import java.util.ServiceLoader;
import com.myapp.spi.Plugin;

public class App {
    public static void main(String[] args) {
        // Load all Plugin implementations declared in module-info.java
        ServiceLoader<Plugin> loader = ServiceLoader.load(Plugin.class);
        loader.forEach(plugin -> {
            System.out.println("Found: " + plugin.getName());
            plugin.execute();
        });
    }
}
</code></pre>

      <h4>Compilation & Execution</h4>
      <pre><code class="language-bash">javac -d out/classes \\
    --module-source-path src \\
    src/com.myapp/module-info.java \\
    src/com.myapp/com/myapp/**/*.java

# Run with module path instead of classpath
java --module-path out/classes \\
     --module com.myapp/com.myapp.App

# Create modular JAR
jar --create --file app.jar \\
    --main-class com.myapp.App \\
    -C out/classes .

# Reduce JRE size using jlink
jlink --module-path $JAVA_HOME/jmods:app.jar \\
      --add-modules com.myapp \\
      --output app-runtime
./app-runtime/bin/java -m com.myapp/com.myapp.App
</code></pre>

      <p class="tip"><strong>Benefits:</strong> Strong encapsulation (private by default), explicit dependencies (avoid jar hell), smaller JRE footprint, better security boundaries.</p>

      <h3>2. Collection Factory Methods (Immutable)</h3>
      <pre><code class="language-java">// OLD WAY (pre-Java 9)
List<String> list = new ArrayList<>(Arrays.asList("a", "b", "c"));
// Still mutable, requires 3 imports

// JAVA 9+ IMMUTABLE FACTORIES
List<String> list = List.of("a", "b", "c");      // immutable, no nulls
Set<Integer> set = Set.of(1, 2, 3);              // immutable, unordered
Map<String, Integer> map = Map.of(
    "one", 1,
    "two", 2,
    "three", 3
);

// For larger maps (varargs have limit):
Map<String, Integer> bigMap = Map.ofEntries(
    Map.entry("first", 1),
    Map.entry("second", 2),
    Map.entry("third", 3)
);

// Try to modify:
list.add("d");  // UnsupportedOperationException
set.remove(1);  // UnsupportedOperationException
map.put("four", 4);  // UnsupportedOperationException

// Null not allowed:
List.of("a", null);  // NullPointerException
</code></pre>

      <h3>3. Stream API Enhancements</h3>
      <pre><code class="language-java">// takeWhile: stop when predicate fails
Stream.of(1, 2, 3, 4, 5, 1, 2)
    .takeWhile(n -> n < 4)
    .forEach(System.out::println);
// Output: 1, 2, 3 (stops at 4)

// dropWhile: skip while predicate is true
Stream.of(1, 2, 3, 4, 5, 1, 2)
    .dropWhile(n -> n < 4)
    .forEach(System.out::println);
// Output: 4, 5, 1, 2

// iterate with finite limit (vs infinite pre-9)
Stream.iterate(1, n -> n <= 100, n -> n * 2)
    .forEach(System.out::println);
// Output: 1, 2, 4, 8, 16, 32, 64

// ofNullable: stream of 0 or 1 element
Stream.ofNullable(null).count();      // 0
Stream.ofNullable("value").count();   // 1
Optional.of("x").stream();             // Stream["x"]

// Use in stream chain:
List<String> values = List.of("a", null, "b", null, "c");
values.stream()
    .flatMap(Stream::ofNullable)
    .forEach(System.out::println);
// Output: a, b, c
</code></pre>

      <h3>4. Optional Enhancements</h3>
      <pre><code class="language-java">// ifPresentOrElse: handle both present and empty cases
Optional.of("Alice")
    .ifPresentOrElse(
        name -> System.out.println("Hello, " + name),
        () -> System.out.println("No user found")
    );

// or: get alternative Optional
Optional<String> fallback = Optional.empty()
    .or(() -> Optional.of("default"))
    .or(() -> Optional.of("another default"));
System.out.println(fallback.get());  // "default"

// stream: convert Optional to Stream
List<String> names = List.of(
    Optional.of("Alice"),
    Optional.empty(),
    Optional.of("Bob")
);
names.stream()
    .flatMap(Optional::stream)
    .forEach(System.out::println);
// Output: Alice, Bob
</code></pre>` }} />
    ),
  },
  {
    id: 'java10',
    title: 'Java 10 (2018): var Keyword',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 10 (2018): var Keyword</h2>

      <h3>Local Variable Type Inference (var)</h3>
      <p class="important"><strong>What it is:</strong> Compiler infers type from initializer. Still fully statically typed. Only for local variables.</p>

      <h4>Basic Usage</h4>
      <pre><code class="language-java">// Type is inferred from right-hand side
var name = "Alice";                    // String
var age = 30;                          // int
var score = 95.5;                      // double
var list = new ArrayList<String>();   // ArrayList<String>
var map = new HashMap<String, Integer>();  // HashMap<String,Integer>

// Method calls infer return type
var now = LocalDateTime.now();         // LocalDateTime
var files = Files.list(Paths.get(".")); // Stream<Path>

// Type is determined at compile time (not runtime)
var x = 5;
x = "hello";  // COMPILE ERROR: String cannot assign to int
</code></pre>

      <h4>In Loops and Iteration</h4>
      <pre><code class="language-java">// for-loop
List<String> words = List.of("hello", "world", "java");
for (var word : words) {
    System.out.println(word);  // word is String
}

// Traditional for-loop
for (var i = 0; i < 10; i++) {
    System.out.println(i);  // i is int
}

// Map iteration
Map<String, Integer> scores = Map.of("Alice", 95, "Bob", 87);
for (var entry : scores.entrySet()) {
    System.out.println(entry.getKey() + ": " + entry.getValue());
}
</code></pre>

      <h4>With Try-with-Resources</h4>
      <pre><code class="language-java">// Old way: verbose
try (BufferedReader br = new BufferedReader(new FileReader("file.txt"))) {
    String line;
    while ((line = br.readLine()) != null) {
        System.out.println(line);
    }
}

// Java 10+: var everywhere
try (var br = new BufferedReader(new FileReader("file.txt"))) {
    String line;
    while ((line = br.readLine()) != null) {
        System.out.println(line);
    }
}

// Multiple resources
try (var br = new BufferedReader(new FileReader("input.txt"));
     var bw = new BufferedWriter(new FileWriter("output.txt"))) {
    // ...
}
</code></pre>

      <h4>Limitations (var cannot be used)</h4>
      <pre><code class="language-java">// ✗ Method parameters
public void process(var list) { }  // ERROR

// ✗ Return types
public var getData() { return "x"; }  // ERROR

// ✗ Class fields
class Person {
    var name = "Alice";  // ERROR
}

// ✗ Catch parameters (until Java 14)
try { ... } catch (var e) { }  // ERROR (pre-Java 14)

// ✗ Without initializer
var x;  // ERROR: no initializer

// ✗ Null initializer (too broad)
var x = null;  // ERROR: type is indeterminate
</code></pre>

      <h3>Unmodifiable Copy Methods</h3>
      <pre><code class="language-java">// Make defensive copies (immutable views)
List<String> original = new ArrayList<>(List.of("a", "b", "c"));
List<String> copy = List.copyOf(original);

Set<Integer> setCopy = Set.copyOf(Set.of(1, 2, 3));
Map<String, Integer> mapCopy = Map.copyOf(Map.of("x", 1, "y", 2));

// Original is still mutable
original.add("d");
System.out.println(original);  // [a, b, c, d]
System.out.println(copy);      // [a, b, c] (unchanged)

// In streams
List<String> immutable = someStream
    .collect(Collectors.toUnmodifiableList());
Set<String> immutableSet = someStream
    .collect(Collectors.toUnmodifiableSet());
</code></pre>` }} />
    ),
  },
  {
    id: 'java11',
    title: 'Java 11 (2018 LTS): String APIs, HttpClient, Files',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 11 (2018 LTS): String APIs, HttpClient, Files</h2>

      <h3>1. String Methods</h3>
      <pre><code class="language-java">// isBlank: checks for whitespace-only strings (Unicode-aware)
"  ".isBlank();                 // true
"  hello  ".isBlank();          // false
"".isBlank();                   // true

// strip: Unicode-aware trim (removes leading/trailing whitespace)
"  hello  ".strip();            // "hello"
" hello ".strip();    // "hello" (includes non-breaking space)

String s = "  hello  ";
s.stripLeading();               // "hello  "
s.stripTrailing();              // "  hello"

// repeat: duplicate string
"ha".repeat(3);                 // "hahaha"
"abc".repeat(0);                // ""
"x".repeat(5);                  // "xxxxx"

// lines: split string into stream of lines
String multiline = "line1\\nline2\\nline3";
multiline.lines()
    .forEach(System.out::println);
// Output: line1, line2, line3

// Practical: read file with lines()
Files.readString(Path.of("file.txt"))
    .lines()
    .filter(line -> !line.isBlank())
    .map(String::trim)
    .forEach(System.out::println);
</code></pre>

      <h3>2. Files I/O Methods</h3>
      <pre><code class="language-java">import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

// Read entire file as string
String content = Files.readString(Path.of("file.txt"));
String content2 = Files.readString(Path.of("file.txt"),
                                    StandardCharsets.UTF_8);

// Write string to file
Files.writeString(Path.of("output.txt"), "Hello, World!");
Files.writeString(Path.of("output.txt"), "Hello",
                  StandardCharsets.UTF_8,
                  StandardOpenOption.CREATE_NEW);

// Append to file
Files.writeString(Path.of("output.txt"), "\\nMore content",
                  StandardOpenOption.APPEND);

// Read all lines
List<String> lines = Files.readAllLines(Path.of("file.txt"));

// Read all bytes
byte[] bytes = Files.readAllBytes(Path.of("binary.bin"));
</code></pre>

      <h3>3. HttpClient (Modern HTTP)</h3>
      <p class="important"><strong>Why:</strong> HttpURLConnection is ancient and clunky. HttpClient supports HTTP/2, async, modern patterns.</p>

      <h4>Synchronous GET</h4>
      <pre><code class="language-java">import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.URI;
import java.time.Duration;

// Create client (reuse for multiple requests)
HttpClient client = HttpClient.newBuilder()
    .version(HttpClient.Version.HTTP_2)
    .followRedirects(HttpClient.Redirect.NORMAL)
    .connectTimeout(Duration.ofSeconds(10))
    .build();

// Build request
HttpRequest request = HttpRequest.newBuilder()
    .uri(URI.create("https://api.example.com/users"))
    .GET()
    .timeout(Duration.ofSeconds(30))
    .header("Accept", "application/json")
    .build();

// Send and get response
HttpResponse<String> response = client.send(request,
    HttpResponse.BodyHandlers.ofString());

System.out.println("Status: " + response.statusCode());
System.out.println("Body: " + response.body());

if (response.statusCode() == 200) {
    String json = response.body();
    // parse JSON here
}
</code></pre>

      <h4>Asynchronous GET</h4>
      <pre><code class="language-java">// Non-blocking, returns CompletableFuture
client.sendAsync(request, HttpResponse.BodyHandlers.ofString())
    .thenApply(HttpResponse::body)
    .thenAccept(body -> System.out.println("Response: " + body))
    .exceptionally(e -> {
        System.err.println("Error: " + e.getMessage());
        return null;
    });

// Or with explicit completion
client.sendAsync(request, HttpResponse.BodyHandlers.ofString())
    .whenComplete((response, exception) -> {
        if (exception != null) {
            exception.printStackTrace();
        } else {
            System.out.println("Got: " + response.body());
        }
    });
</code></pre>

      <h4>POST with JSON Body</h4>
      <pre><code class="language-java">String jsonBody = """
    {
      "name": "Alice",
      "email": "alice@example.com"
    }
    """;

HttpRequest post = HttpRequest.newBuilder()
    .uri(URI.create("https://api.example.com/users"))
    .header("Content-Type", "application/json")
    .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
    .build();

HttpResponse<String> response = client.send(post,
    HttpResponse.BodyHandlers.ofString());

System.out.println("Created: " + response.statusCode());
</code></pre>

      <h4>Different Response Body Handlers</h4>
      <pre><code class="language-java">// String body
HttpResponse<String> resp1 = client.send(request,
    HttpResponse.BodyHandlers.ofString());

// Byte array (for binary)
HttpResponse<byte[]> resp2 = client.send(request,
    HttpResponse.BodyHandlers.ofByteArray());

// Write to file
HttpResponse<Path> resp3 = client.send(request,
    HttpResponse.BodyHandlers.ofFile(Path.of("output.bin")));

// Stream processing
HttpResponse<Stream<String>> resp4 = client.send(request,
    HttpResponse.BodyHandlers.ofLines());
resp4.body().forEach(System.out::println);

// Custom handler (discard body, just status)
HttpResponse<Void> resp5 = client.send(request,
    HttpResponse.BodyHandlers.discarding());
</code></pre>

      <h3>4. Single-File Programs</h3>
      <pre><code class="language-java">// File: Hello.java
public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
</code></pre>

      <pre><code class="language-bash"># Pre-Java 11: must compile first
javac Hello.java
java Hello

# Java 11+: run directly (no separate compile step)
java Hello.java
# Output: Hello, World!
</code></pre>

      <h3>5. Predicate.not()</h3>
      <pre><code class="language-java">import java.util.function.Predicate;

List<String> words = List.of("hello", "", "world", "", "java");

// Old way: verbose
words.stream()
    .filter(s -> !s.isBlank())
    .forEach(System.out::println);

// Java 11+: cleaner
words.stream()
    .filter(Predicate.not(String::isBlank))
    .forEach(System.out::println);

// Works with custom predicates too
Predicate<Integer> isEven = n -> n % 2 == 0;
List<Integer> nums = List.of(1, 2, 3, 4, 5, 6);
nums.stream()
    .filter(Predicate.not(isEven))
    .forEach(System.out::println);  // 1, 3, 5
</code></pre>` }} />
    ),
  },
  {
    id: 'java12-15',
    title: 'Java 12-15: Switch Expressions, Text Blocks, Sealed Classes',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 12-15: Switch Expressions, Text Blocks, Sealed Classes</h2>

      <h3>Switch Expressions (Java 12 preview, Java 14 final)</h3>
      <p class="tip"><strong>Covered in Chapter 3.</strong> Mark here: Java 12 introduced preview, Java 14+ is final.</p>

      <pre><code class="language-java">// Old switch statement
String day = "Monday";
String type;
switch (day) {
    case "Saturday":
    case "Sunday":
        type = "weekend";
        break;
    default:
        type = "weekday";
        break;
}

// Java 12+ switch expression
String type = switch (day) {
    case "Saturday", "Sunday" -> "weekend";
    case "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" -> "weekday";
    default -> "unknown";
};

// With blocks
int value = switch (status) {
    case "active" -> {
        System.out.println("Processing active");
        yield 1;  // yield returns value from block
    }
    case "inactive" -> {
        System.out.println("Skipping inactive");
        yield 0;
    }
    default -> -1;
};
</code></pre>

      <h3>Text Blocks (Java 13 preview, Java 15 final)</h3>
      <p class="important"><strong>What it is:</strong> Multi-line strings with automatic indentation handling. No escaping needed for quotes.</p>

      <h4>Basic Syntax</h4>
      <pre><code class="language-java">// OLD: Messy string concatenation
String json = "{\\n" +
    "  \\"name\\": \\"Alice\\",\\n" +
    "  \\"age\\": 30,\\n" +
    "  \\"active\\": true\\n" +
    "}";

// JAVA 15+: Text block (triple quotes)
String json = """
    {
      "name": "Alice",
      "age": 30,
      "active": true
    }
    """;

// HTML example
String html = """
    <html>
        <head>
            <title>Example</title>
        </head>
        <body>
            <p>Hello, World!</p>
</body>
    </html>
    """;

// SQL example
String query = """
    SELECT * FROM users
    WHERE age > 18
    AND status = 'active'
    ORDER BY created_at DESC
    """;
</code></pre>

      <h4>Formatting & Whitespace</h4>
      <pre><code class="language-java">// Indentation is automatically stripped based on closing """
String output = """
    Line one
    Line two
      Line three (extra indent preserved)
    Line four
    """;
// Result:
// "Line one\\nLine two\\n  Line three (extra indent preserved)\\nLine four\\n"

// Using .formatted() (like String.format)
String greeting = """
    Hello, %s!
    Your age is %d.
    """.formatted("Alice", 30);

// Suppress final newline with trailing backslash
String oneLine = """
    This is a \\
    single line""";
// Result: "This is a single line"

// Raw string (rarely used)
String raw = "C:\\\\Users\\\\Alice\\\\Documents";  // before 15
String raw15 = """
    C:\\Users\\Alice\\Documents
    """;  // backslashes literal in text blocks
</code></pre>

      <h3>String.indent() and String.transform()</h3>
      <pre><code class="language-java">// indent: add/remove indentation from each line
String code = "hello\\nworld\\njava";
String indented = code.indent(4);
// Result: "    hello\\n    world\\n    java\\n"

String dedented = "    line1\\n    line2".indent(-4);
// Result: "line1\\nline2"

// transform: apply function to string
"42".transform(Integer::parseInt);              // 42
"HELLO".transform(String::toLowerCase);         // "hello"
"  spaced  ".transform(String::trim);           // "spaced"

// Practical: format JSON with indentation
String json = """
    {"name":"Alice","age":30}
    """;
String pretty = JsonUtils.format(json)
    .indent(2);  // indent pretty-printed result
</code></pre>

      <h3>Sealed Classes (Java 15 preview, Java 17 final)</h3>
      <p class="tip"><strong>Covered in Chapter 5.</strong> Mark here: Java 15 introduced preview, Java 17+ is final.</p>

      <p class="note"><strong>Syntax:</strong> \`sealed class Name permits Child1, Child2 { ... }\`</p>

      <pre><code class="language-java">// Define allowed subclasses
sealed class Shape permits Circle, Rectangle, Triangle {
    abstract double area();
}

final class Circle extends Shape {
    final double radius;
    Circle(double radius) { this.radius = radius; }
    @Override double area() { return Math.PI * radius * radius; }
}

final class Rectangle extends Shape {
    final double width, height;
    Rectangle(double w, double h) { width = w; height = h; }
    @Override double area() { return width * height; }
}

sealed class Triangle extends Shape permits RightTriangle {
    // can further restrict
}

final class RightTriangle extends Triangle {
    double base, height;
    @Override double area() { return base * height / 2; }
}

// Usage: compiler ensures all cases covered
double calculateArea(Shape shape) {
    if (shape instanceof Circle c) {
        return c.area();
    } else if (shape instanceof Rectangle r) {
        return r.area();
    } else if (shape instanceof Triangle t) {
        return t.area();
    }
    // No default needed; compiler verifies exhaustiveness
}
</code></pre>

      <h3>Helpful NullPointerException Messages (Java 14)</h3>
      <pre><code class="language-java">// Pre-Java 14:
String city = user.getAddress().getCity().toUpperCase();
// Exception: NullPointerException (useless!)

// Java 14+: includes details
// Exception message:
// Cannot invoke "String.toUpperCase()" because the return value of
// "com.example.Address.getCity()" is null

// Compiler actually tells you which method returned null!
// This is automatic — no code change needed.
</code></pre>

      <h3>Pattern Matching for instanceof (Java 14 preview, Java 16 final)</h3>
      <p class="important"><strong>Covered in Chapter 3.</strong> Here's the basic syntax:</p>

      <pre><code class="language-java">// OLD: cast after type check
if (obj instanceof String) {
    String s = (String) obj;  // manual cast
    System.out.println(s.length());
}

// JAVA 14+: pattern matching
if (obj instanceof String s) {
    System.out.println(s.length());  // s already cast
}

// With condition
if (obj instanceof String s && s.length() > 5) {
    System.out.println("Long string: " + s);
}

// Composite with other types
Object obj = "hello";
if (obj instanceof String s) {
    System.out.println("String of length " + s.length());
} else if (obj instanceof Integer i) {
    System.out.println("Integer: " + i);
} else if (obj instanceof List<?> list) {
    System.out.println("List with " + list.size() + " items");
}
</code></pre>

      <h3>String.formatted()</h3>
      <pre><code class="language-java">// Same as String.format() but as method
String formatted = "Hello, %s! You are %d years old."
    .formatted("Alice", 30);
// Result: "Hello, Alice! You are 30 years old."

// Works in text blocks
String message = """
    Name: %s
    Age: %d
    Score: %.1f
    """.formatted("Bob", 25, 87.5);
</code></pre>` }} />
    ),
  },
  {
    id: 'java16-17',
    title: 'Java 16-17 (LTS): Records Final, Pattern Matching, Sealed Classes Final',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 16-17 (LTS): Records Final, Pattern Matching, Sealed Classes Final</h2>

      <h3>Records (Java 14 preview, Java 16 final)</h3>
      <p class="tip"><strong>Covered in Chapter 5 in detail.</strong> Summary here:</p>

      <pre><code class="language-java">// Data class with fields, constructor, equals, hashCode, toString
record Person(String name, int age) {
    // Automatically generates:
    // - Constructor: Person(String name, int age)
    // - Field accessors: name(), age()
    // - equals(), hashCode(), toString()
}

// Usage
Person alice = new Person("Alice", 30);
System.out.println(alice);              // Person[name=Alice, age=30]
System.out.println(alice.name());       // Alice
System.out.println(alice.age());        // 30

// Custom validation in constructor
record Point(int x, int y) {
    public Point {  // compact constructor (no params)
        if (x < 0 || y < 0) {
            throw new IllegalArgumentException("Coordinates must be non-negative");
        }
    }
}

// With methods
record Rectangle(double width, double height) {
    public double area() {
        return width * height;
    }

    public boolean isSquare() {
        return width == height;
    }
}

// Records are immutable
Point p = new Point(5, 10);
p.x = 20;  // ERROR: cannot assign to field
</code></pre>

      <h3>Pattern Matching for instanceof (Final in Java 16)</h3>
      <pre><code class="language-java">// Already shown above, now final (not preview)
Object obj = "test";

if (obj instanceof String s) {
    System.out.println("Length: " + s.length());
}

// Nested patterns with records (Java 21 feature, but instanceof part is 16)
record User(String name, int age) {}
Object user = new User("Alice", 30);

if (user instanceof User u) {
    System.out.println(u.name() + " is " + u.age());
}
</code></pre>

      <h3>Stream.toList()</h3>
      <pre><code class="language-java">import java.util.stream.Collectors;

// OLD: verbose collector
List<String> result = stream
    .collect(Collectors.toList());

// JAVA 16+: shorthand
List<String> result = stream
    .toList();  // returns unmodifiable List

// Note: returns unmodifiable list (can't add/remove)
List<Integer> nums = List.of(1, 2, 3).stream()
    .filter(n -> n > 1)
    .toList();  // [2, 3]
nums.add(4);   // UnsupportedOperationException
</code></pre>

      <h3>Stream.mapMulti()</h3>
      <pre><code class="language-java">// Generate multiple outputs per input (like flatMap but more explicit)
List<Integer> inputs = List.of(1, 2, 3);

List<Integer> result = inputs.stream()
    .mapMulti((num, consumer) -> {
        consumer.accept(num);        // emit original
        consumer.accept(num * 10);   // emit multiplied
    })
    .toList();
// Result: [1, 10, 2, 20, 3, 30]

// More practical: flatten optional fields
record Order(String id, List<Item> items) {}
record Item(String sku, int qty) {}

List<Item> allItems = orders.stream()
    .mapMulti((order, consumer) -> {
        order.items().forEach(consumer);
    })
    .toList();

// Equivalent to flatMap:
List<Item> allItems2 = orders.stream()
    .flatMap(order -> order.items().stream())
    .toList();
</code></pre>

      <h3>Sealed Classes (Final in Java 17)</h3>
      <p class="tip"><strong>Already shown in Java 15 section.</strong> Java 17 just finalizes the feature (not preview).</p>

      <h3>Pattern Matching for switch (Java 17 preview)</h3>
      <p class="tip"><strong>Covered in Chapter 3, Java 21 final.</strong> Java 17 introduces preview version:</p>

      <pre><code class="language-java">// Java 17+ (preview, final in 21)
Object obj = 42;

String result = switch (obj) {
    case Integer i -> "Integer: " + i;
    case String s -> "String: " + s;
    case Double d -> "Double: " + d;
    default -> "Unknown";
};

// With guards
int value = switch (obj) {
    case Integer i when i > 0 -> i * 2;
    case Integer i when i < 0 -> -i;
    case Integer i -> 0;  // i == 0
    default -> -1;
};
</code></pre>

      <h3>RandomGenerator API</h3>
      <pre><code class="language-java">import java.util.random.RandomGenerator;

// Modern replacement for java.util.Random
RandomGenerator rng = RandomGenerator.of("L64X128MixRandom");

// Generate random numbers
int num = rng.nextInt(100);           // 0-99
double decimal = rng.nextDouble();     // 0.0-1.0
long bigNum = rng.nextLong(1000000);  // 0-999999
boolean flag = rng.nextBoolean();

// Stream generation
rng.ints(10, 0, 100)          // 10 random ints 0-99
    .forEach(System.out::println);

rng.longs(5, 0, 1000)         // 5 random longs 0-999
    .forEach(System.out::println);

// Different algorithm options
// Math.random() still works (uses default)
double x = Math.random();

// Old Random class still works
var oldRng = new java.util.Random();
int y = oldRng.nextInt(100);
</code></pre>` }} />
    ),
  },
  {
    id: 'java18-20',
    title: 'Java 18-20: Web Server, Virtual Threads (Preview)',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 18-20: Web Server, Virtual Threads (Preview)</h2>

      <h3>Simple Web Server (Java 18)</h3>
      <p class="important"><strong>What it is:</strong> Built-in static file server, no dependencies needed.</p>

      <pre><code class="language-bash"># Start default server (localhost:8000, serving current dir)
jwebserver

# Custom port
jwebserver -p 9090

# Custom directory
jwebserver -d /var/www

# Both
jwebserver -p 3000 -d /home/user/public_html

# Set bind address
jwebserver -b 0.0.0.0 -p 8000

# Then access: curl http://localhost:8000/
</code></pre>

      <p class="note"><strong>Use case:</strong> Quick demo server, testing, single-page app development. Not production.</p>

      <h3>Virtual Threads Introduction (Java 19-20 preview)</h3>
      <p class="tip"><strong>Covered in Chapter 9 (Concurrency).</strong> Full feature in Java 21. Here's quick intro:</p>

      <pre><code class="language-java">// OLD: limited by expensive OS threads
ExecutorService executor = Executors.newFixedThreadPool(10);
for (int i = 0; i < 1000; i++) {
    executor.submit(() -> {
        doSomeWork();  // but only 10 threads total
    });
}

// JAVA 19+ Virtual Threads (lightweight, millions possible)
try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {
    for (int i = 0; i < 100_000; i++) {
        executor.submit(() -> {
            doSomeWork();  // each task gets its own virtual thread!
        });
    }
}  // wait for all to complete

// Direct creation
Thread vThread = Thread.ofVirtual()
    .name("worker-1")
    .start(() -> System.out.println("Running in virtual thread"));

// Not for CPU-intensive work (still limited by CPU cores)
// Best for I/O-bound work (network, database, file I/O)
</code></pre>

      <h3>Javadoc @snippet Tag (Java 18)</h3>
      <pre><code class="language-java">/**
 * Processes a list of numbers and returns the sum.
 *
 * {@snippet :
 * var numbers = List.of(1, 2, 3, 4, 5);
 * int sum = numbers.stream()
 *     .mapToInt(Integer::intValue)
 *     .sum();
 * System.out.println(sum);  // @highlight substring="sum"
 * }
 *
 * @param numbers the input numbers
 * @return the sum
 */
public int sum(List<Integer> numbers) {
    return numbers.stream().mapToInt(Integer::intValue).sum();
}
</code></pre>

      <h3>UTF-8 Default Charset (Java 18)</h3>
      <pre><code class="language-java">// Pre-Java 18: default charset depends on OS/locale
Charset old = Charset.defaultCharset();  // could be Cp1252, UTF-8, etc.

// Java 18+: always UTF-8
Charset ch = Charset.defaultCharset();   // always StandardCharsets.UTF_8

// Always safe to assume UTF-8 for:
Files.readString(path);
Files.writeString(path, content);
new String(bytes);
</code></pre>` }} />
    ),
  },
  {
    id: 'java21',
    title: 'Java 21 (2023 LTS): Virtual Threads Final, Record Patterns, Sequenced Collections',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 21 (2023 LTS): Virtual Threads Final, Record Patterns, Sequenced Collections</h2>

      <h3>Virtual Threads (Final)</h3>
      <p class="tip"><strong>Detailed in Chapter 9.</strong> Quick reference:</p>

      <pre><code class="language-java">import java.util.concurrent.Executors;

// Create executor that uses virtual threads
ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor();

// Submit tasks (each gets a virtual thread)
for (int i = 0; i < 10_000; i++) {
    executor.submit(() -> {
        // Blocking call (e.g., HTTP request, database query)
        // Doesn't waste OS thread; virtual thread is parked
        String result = makeHttpRequest();
        System.out.println(result);
    });
}

executor.shutdown();
executor.awaitTermination(1, TimeUnit.MINUTES);

// Direct thread creation
Thread vthread = Thread.ofVirtual()
    .name("request-handler-%d")
    .start(() -> {
        handleRequest();  // I/O-bound work
    });

// Check if virtual
if (Thread.currentThread().isVirtual()) {
    System.out.println("Running in virtual thread");
}
</code></pre>

      <h3>Record Patterns (Final)</h3>
      <p class="important"><strong>What it is:</strong> Deconstruct records in patterns. Works with instanceof and switch.</p>

      <pre><code class="language-java">record Point(int x, int y) {}
record Line(Point start, Point end) {}
record Circle(Point center, int radius) {}

// Deconstruct in instanceof
Object obj = new Point(3, 4);
if (obj instanceof Point(int x, int y)) {
    System.out.println("Point at (" + x + ", " + y + ")");
}

// Nested record patterns
Shape shape = new Line(new Point(0, 0), new Point(10, 10));
if (shape instanceof Line(Point(int x1, int y1), Point(int x2, int y2))) {
    double length = Math.hypot(x2 - x1, y2 - y1);
    System.out.println("Line length: " + length);
}

// In switch statement
double area = switch (shape) {
    case Circle(Point c, int r) -> Math.PI * r * r;
    case Rectangle(int w, int h) -> w * h;
    case Line(Point start, Point end) -> 0;  // lines have no area
};

// With wildcard (_) for unused fields
if (shape instanceof Circle(Point _, int r)) {
    System.out.println("Radius: " + r);  // center not used
}

// Guard expressions
if (shape instanceof Point(int x, int y) && x == y) {
    System.out.println("Point is on diagonal");
}
</code></pre>

      <h3>Sequenced Collections</h3>
      <p class="important"><strong>What it is:</strong> Every ordered collection now has first/last access. New interfaces: SequencedCollection, SequencedSet, SequencedMap.</p>

      <h4>SequencedCollection (List, Deque, etc.)</h4>
      <pre><code class="language-java">List<String> list = new ArrayList<>(List.of("a", "b", "c", "d"));

// New methods
list.getFirst();          // "a"
list.getLast();           // "d"
list.removeFirst();       // removes "a"
list.removeLast();        // removes "d"
list.addFirst("z");       // prepend
list.addLast("w");        // append

// Reversed view
SequencedCollection<String> reversed = list.reversed();
reversed.stream().forEach(System.out::println);  // d, c, b, a

// Works with Deque too
Deque<Integer> deque = new LinkedList<>(List.of(1, 2, 3, 4, 5));
deque.getFirst();         // 1
deque.getLast();          // 5
</code></pre>

      <h4>SequencedSet (LinkedHashSet, etc.)</h4>
      <pre><code class="language-java">SequencedSet<String> set = new LinkedHashSet<>(Set.of("x", "y", "z"));

set.getFirst();           // "x" (insertion order)
set.getLast();            // "z"
set.reversed();           // views in reverse order

// Iterator respects order
set.stream().forEach(System.out::println);  // x, y, z
</code></pre>

      <h4>SequencedMap (LinkedHashMap, etc.)</h4>
      <pre><code class="language-java">SequencedMap<String, Integer> map = new LinkedHashMap<>();
map.put("alpha", 1);
map.put("beta", 2);
map.put("gamma", 3);

// Entry access
Map.Entry<String, Integer> first = map.firstEntry();   // alpha=1
Map.Entry<String, Integer> last = map.lastEntry();     // gamma=3

// Remove and return
Map.Entry<String, Integer> removed = map.pollFirstEntry();  // removes alpha
removed = map.pollLastEntry();  // removes gamma

// Sequenced views
SequencedCollection<String> keys = map.sequencedKeySet();
SequencedCollection<Integer> values = map.sequencedValues();
SequencedCollection<Map.Entry<String, Integer>> entries = map.sequencedEntrySet();

// Reversed
map.reversed().forEach((k, v) ->
    System.out.println(k + ": " + v)
);  // gamma: 3, beta: 2, alpha: 1
</code></pre>

      <h3>Pattern Matching for switch (Final)</h3>
      <p class="tip"><strong>Covered in Chapter 3, Java 17+ preview.</strong> Java 21 finalizes.</p>

      <pre><code class="language-java">// Guard expressions
int days = switch (month) {
    case "January", "March", "May" -> 31;
    case "April", "June" -> 30;
    case "February" when isLeapYear() -> 29;
    case "February" -> 28;
    default -> throw new IllegalArgumentException("Unknown month");
};

// Type patterns
String result = switch (obj) {
    case String s when s.length() > 5 -> "Long string: " + s;
    case String s -> "Short string: " + s;
    case Integer i when i > 0 -> "Positive integer";
    case Integer i -> "Non-positive integer";
    case null -> "Null value";
    default -> "Other";
};
</code></pre>` }} />
    ),
  },
  {
    id: 'java22-24',
    title: 'Java 22-24: Unnamed Variables, Unnamed Classes, Stream.gather()',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 22-24: Unnamed Variables, Unnamed Classes, Stream.gather()</h2>

      <h3>Unnamed Variables (_) (Java 22 final)</h3>
      <p class="important"><strong>What it is:</strong> Use \`_\` for variables you don't intend to use. Signals intent and avoids "variable not used" warnings.</p>

      <h4>In Catch Blocks</h4>
      <pre><code class="language-java">// OLD: forced to name exception even if unused
try {
    risky();
} catch (IOException ignored) {
    log.warn("IO error occurred");
}

// JAVA 22+: use unnamed variable
try {
    risky();
} catch (IOException _) {
    log.warn("IO error occurred");
}

// Multiple unnamed variables
try {
    process();
} catch (IOException _ | TimeoutException _) {
    handleError();
}
</code></pre>

      <h4>In Patterns</h4>
      <pre><code class="language-java">record Point(int x, int y) {}

// Only care about x coordinate
if (point instanceof Point(int x, _)) {
    System.out.println("X coordinate: " + x);
}

// Don't care about any deconstructed values
if (shape instanceof Rectangle(_, _)) {
    System.out.println("It's a rectangle");
}
</code></pre>

      <h4>In Loops</h4>
      <pre><code class="language-java">// Just iterate, don't use element
List<String> items = List.of("a", "b", "c");
int count = 0;
for (var _ : items) {
    count++;
}

// For traditional loops
for (var _ = 0; _ < 10; _++) {
    doSomething();  // just 10 iterations
}
</code></pre>

      <h4>In Lambdas</h4>
      <pre><code class="language-java">// BiConsumer where we only use first param
BiConsumer<String, Integer> printer = (s, _) ->
    System.out.println(s);

// Function where we ignore input
Function<String, String> constant = _ -> "always this";

// Stream of unused values
Stream.of(1, 2, 3)
    .forEach(_ -> counter++);
</code></pre>

      <h3>Unnamed Classes and Instance Main Methods (Java 22 preview, Java 25 final)</h3>
      <p class="important"><strong>What it is:</strong> Write Hello World without boilerplate. No class declaration needed. Instance main() instead of static.</p>

      <h4>Traditional Java (verbose)</h4>
      <pre><code class="language-java">public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
</code></pre>

      <h4>Java 25+ (simple)</h4>
      <pre><code class="language-java">// File: Hello.java (no class declaration needed!)
void main() {
    System.out.println("Hello, World!");
}
</code></pre>

      <pre><code class="language-bash"># Run directly
java Hello.java
# Output: Hello, World!
</code></pre>

      <h4>With Arguments</h4>
      <pre><code class="language-java">void main(String[] args) {
    if (args.length > 0) {
        System.out.println("Hello, " + args[0]);
    }
}
</code></pre>

      <pre><code class="language-bash">java Hello.java Alice
# Output: Hello, Alice
</code></pre>

      <h4>With Fields and Methods</h4>
      <pre><code class="language-java">// Still an unnamed class, but can have fields
String greeting = "Hello";
int counter = 0;

void main() {
    System.out.println(greeting + ", World!");
    counter++;
    printSummary();
}

void printSummary() {
    System.out.println("Execution count: " + counter);
}
</code></pre>

      <h3>Stream.gather() (Java 22 preview, Java 24 final)</h3>
      <p class="important"><strong>What it is:</strong> Custom intermediate operations on streams. More flexible than map/filter.</p>

      <h4>Windowing</h4>
      <pre><code class="language-java">import java.util.stream.Gatherers;

List<Integer> numbers = List.of(1, 2, 3, 4, 5, 6, 7, 8, 9);

// Sliding window of 3
numbers.stream()
    .gather(Gatherers.windowFixed(3))
    .forEach(System.out::println);
// Output:
// [1, 2, 3]
// [4, 5, 6]
// [7, 8, 9]

// Sliding window with overlap
numbers.stream()
    .gather(Gatherers.windowSliding(3))
    .forEach(System.out::println);
// Output:
// [1, 2, 3]
// [2, 3, 4]
// [3, 4, 5]
// ...
</code></pre>

      <h4>Scanning (Running Accumulation)</h4>
      <pre><code class="language-java">List<Integer> nums = List.of(1, 2, 3, 4, 5);

// Running sum
nums.stream()
    .gather(Gatherers.scan(() -> 0, Integer::sum))
    .forEach(System.out::println);
// Output: 1, 3, 6, 10, 15

// Running product
nums.stream()
    .gather(Gatherers.scan(() -> 1, (a, b) -> a * b))
    .forEach(System.out::println);
// Output: 1, 2, 6, 24, 120
</code></pre>

      <h4>Custom Gatherer</h4>
      <pre><code class="language-java">// Custom: emit every Nth element
Gatherer<Integer, ?, Integer> everyNth =
    Gatherer.ofSequential(
        () -> new int[]{0},  // state: counter
        (state, element, downstream) -> {
            state[0]++;
            if (state[0] % 2 == 0) {  // every 2nd
                return downstream.push(element);
            }
            return true;  // continue
        }
    );

numbers.stream()
    .gather(everyNth)
    .forEach(System.out::println);
// Output: 2, 4, 6, 8
</code></pre>

      <h3>Class-File API (Java 24 final)</h3>
      <p class="tip"><strong>Advanced feature:</strong> Read/write .class files programmatically. Used by frameworks, code generators.</p>

      <pre><code class="language-java">import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.nio.file.Path;

// Read class file
ClassFile cf = ClassFile.of();
ClassModel model = cf.parse(Path.of("MyClass.class"));

// Inspect
System.out.println("Class: " + model.thisClass());
model.methods().forEach(m ->
    System.out.println("  Method: " + m.methodName())
);

// Modify and write
ClassFile cf2 = ClassFile.of();
ClassModel newModel = cf2.build(
    model.thisClass(),
    cb -> {
        cb.withMethods(model.methods());
        cb.withFields(model.fields());
        // Can add/remove methods, fields, etc.
    }
);
</code></pre>

      <h3>Foreign Function & Memory API (Java 22 final)</h3>
      <p class="tip"><strong>Advanced feature:</strong> Call native C functions and access off-heap memory without JNI boilerplate.</p>

      <pre><code class="language-java">import java.lang.foreign.*;

// Allocate off-heap memory
try (Arena arena = Arena.ofConfined()) {
    MemorySegment segment = arena.allocate(100);

    // Write data
    segment.set(ValueLayout.JAVA_INT, 0, 42);
    segment.set(ValueLayout.JAVA_INT, 4, 99);

    // Read data
    int val1 = segment.get(ValueLayout.JAVA_INT, 0);  // 42
    int val2 = segment.get(ValueLayout.JAVA_INT, 4);  // 99

    // Call native function (example: strlen)
    Linker linker = Linker.nativeLinker();
    SymbolLookup stdlib = linker.defaultLookup();

    MemorySegment strAddr = arena.allocateUtf8String("hello");
    MethodHandle strlen = linker.downcallHandle(
        stdlib.find("strlen").get(),
        FunctionDescriptor.of(
            ValueLayout.JAVA_LONG,
            ValueLayout.ADDRESS
        )
    );

    long length = (long) strlen.invoke(strAddr);  // 5
    System.out.println("Length: " + length);
}
// Memory auto-freed when arena closes
</code></pre>

      <h3>Markdown in Javadoc (Java 23)</h3>
      <pre><code class="language-java">/**
 * # Main heading
 *
 * This is a **bold** text and this is _italic_.
 *
 * ## Sub-heading
 *
 * Example code:
 * \`\`\`java
 * var list = List.of("a", "b");
 * list.forEach(System.out::println);
 * \`\`\`
 *
 * - First item
 * - Second item
 * - Third item
 *
 * @param items the items to process
 * @return the result
 */
public List<String> process(List<String> items) {
    return items;
}
</code></pre>

      <h3>Primitive Types in Patterns (Java 23)</h3>
      <pre><code class="language-java">// Pre-Java 23: couldn't use primitives in patterns
// Java 23+: can match primitive types
Object obj = 42;

if (obj instanceof int i) {
    System.out.println("Integer: " + i);
}

// In switch
String type = switch (obj) {
    case int i when i > 0 -> "positive int";
    case int i when i < 0 -> "negative int";
    case int _ -> "zero";
    case double d -> "double: " + d;
    case String s -> "string: " + s;
    default -> "other";
};

// Works with pattern matching too
if (obj instanceof int i && i > 100) {
    System.out.println("Large integer: " + i);
}
</code></pre>` }} />
    ),
  },
  {
    id: 'java25-26',
    title: 'Java 25-26 (LTS/Preview): Value Classes, Scoped Values, Constructor Flexibility',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Java 25-26 (LTS/Preview): Value Classes, Scoped Values, Constructor Flexibility</h2>

      <h3>Flexible Constructor Bodies (Java 25 final)</h3>
      <p class="important"><strong>What it is:</strong> In Java 25, constructors can have statements before super() call (as long as they don't reference this).</p>

      <pre><code class="language-java">class Base {
    int value;
    Base(int value) { this.value = value; }
}

// Pre-Java 25: super() MUST be first
class OldDerived extends Base {
    OldDerived(int value) {
        super(value);  // must be first statement
        System.out.println("Created with " + value);  // only after
    }
}

// JAVA 25+: statements allowed before super()
class NewDerived extends Base {
    NewDerived(int value) {
        // Pre-super work allowed (just not 'this' reference)
        System.out.println("Creating Derived with " + value);
        int adjusted = value * 2;
        super(adjusted);  // super can be anywhere now
        System.out.println("Initialized");
    }
}
</code></pre>

      <h3>Module Import Declarations (Java 25 final)</h3>
      <pre><code class="language-java">// Import all exported packages from a module at once
import module java.base;        // imports all java.* packages from java.base
import module java.sql;         // imports all javax.sql, java.sql packages
import module com.myapp;        // imports all from our module

// Instead of:
import java.lang.*;
import java.util.*;
import java.util.stream.*;
import java.util.function.*;
// ... dozens of import statements

public class App {
    // Can use String, List, Stream, Function, etc. from java.base
}
</code></pre>

      <h3>Value Classes (Java 26 preview)</h3>
      <p class="important"><strong>What it is:</strong> Immutable, identity-free classes optimized for memory efficiency. Part of Project Valhalla.</p>

      <h4>Value Class Basics</h4>
      <pre><code class="language-java">// Value class: no object identity, can be stored flat in arrays
value class Point {
    int x;
    int y;

    Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    double distanceFromOrigin() {
        return Math.sqrt(x * x + y * y);
    }
}

// Usage
Point p1 = new Point(3, 4);
Point p2 = new Point(3, 4);

// No identity (no '==' by object ref)
p1 == p2;  // false (no identity)
p1.equals(p2);  // true (value equality)

// Can be stored flat in arrays (no per-object overhead)
Point[] points = new Point[1000];  // efficient!
// vs regular: new Point[1000] creates 1000 object headers

// Immutable (can't modify)
p1.x = 10;  // ERROR: cannot assign
</code></pre>

      <h4>Primitive Classes (Even Flatter)</h4>
      <pre><code class="language-java">// Primitive class: absolutely no overhead, just data
// (preview within preview, likely Java 27+)
primitive class Complex {
    double real;
    double imag;

    Complex(double real, double imag) {
        this.real = real;
        this.imag = imag;
    }

    Complex add(Complex other) {
        return new Complex(
            this.real + other.real,
            this.imag + other.imag
        );
    }
}

// Stored flat, no object headers
Complex[] numbers = new Complex[1000_000];  // minimal memory
Complex[] matrix = new Complex[1000][1000];  // 2D arrays efficient
</code></pre>

      <h3>Scoped Values (Java 26 final)</h3>
      <p class="important"><strong>What it is:</strong> Thread-local-like mechanism optimized for Virtual Threads. Safe inheritance across threads.</p>

      <h4>Basic Usage</h4>
      <pre><code class="language-java">import java.lang.ScopedValue;

// Declare a scoped value
static final ScopedValue<String> REQUEST_USER = ScopedValue.newInstance();
static final ScopedValue<Integer> REQUEST_ID = ScopedValue.newInstance();

// Set for a scope (runs a callable)
void handleRequest(String userId) {
    ScopedValue.where(REQUEST_USER, userId)
        .run(() -> {
            processRequest();  // can read REQUEST_USER.get()
        });
}

void processRequest() {
    String user = REQUEST_USER.get();
    System.out.println("Processing for: " + user);
}

// Multiple scoped values
void complexOperation(String user, int id) {
    ScopedValue.where(REQUEST_USER, user)
        .where(REQUEST_ID, id)
        .run(() -> {
            System.out.println("User: " + REQUEST_USER.get());
            System.out.println("ID: " + REQUEST_ID.get());
        });
}
</code></pre>

      <h4>With Virtual Threads</h4>
      <pre><code class="language-java">// ScopedValue is virtual-thread friendly
// (unlike ThreadLocal which doesn't scale to millions)
try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {
    for (int i = 0; i < 100_000; i++) {
        final int taskId = i;
        executor.submit(() -> {
            // Each virtual thread can have its own scoped value
            ScopedValue.where(REQUEST_ID, taskId)
                .run(this::handleTask);
        });
    }
}

void handleTask() {
    int id = REQUEST_ID.get();
    // Process with id
}
</code></pre>

      <h3>Advanced Pattern Matching (Java 26)</h3>
      <p class="tip"><strong>Pattern matching continues to improve.</strong> Further integration with expressions and patterns.</p>

      <pre><code class="language-java">// Deeper nesting and more complex patterns
record Pair<T>(T first, T second) {}
record Container(Pair<String> pair) {}

Object obj = new Container(new Pair<>("hello", "world"));

// Complex nested pattern
if (obj instanceof Container(Pair(String s1, String s2))) {
    System.out.println(s1 + " " + s2);  // hello world
}

// Pattern in variable declaration (experimental)
if (obj instanceof Container c) {
    Pair<String> p = c.pair();
    // Traditional destructuring still works alongside new patterns
}
</code></pre>` }} />
    ),
  },
  {
    id: 'feature-matrix',
    title: 'Complete Feature Matrix: Java 9-26',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Complete Feature Matrix: Java 9-26</h2>
      <p class="note">This table shows when each feature first appeared and its status.</p>
      <table class="feature-table">
        <tr>
          <th>Feature</th>
          <th>Introduced</th>
          <th>Status in Latest</th>
          <th>Chapter Reference</th>
        </tr>
        <tr>
          <td>JPMS (Module System)</td>
          <td>Java 9</td>
          <td>Final</td>
          <td>Chapter 10.1</td>
        </tr>
        <tr>
          <td>Collection Factory Methods (List.of, etc.)</td>
          <td>Java 9</td>
          <td>Final</td>
          <td>Chapter 10.2</td>
        </tr>
        <tr>
          <td>Stream.takeWhile, dropWhile</td>
          <td>Java 9</td>
          <td>Final</td>
          <td>Chapter 10.3</td>
        </tr>
        <tr>
          <td>Stream.ofNullable</td>
          <td>Java 9</td>
          <td>Final</td>
          <td>Chapter 10.3</td>
        </tr>
        <tr>
          <td>Optional.or, ifPresentOrElse, stream</td>
          <td>Java 9</td>
          <td>Final</td>
          <td>Chapter 10.4</td>
        </tr>
        <tr>
          <td>var (Local Variable Type Inference)</td>
          <td>Java 10</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>List.copyOf, Set.copyOf, Map.copyOf</td>
          <td>Java 10</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>String.isBlank, strip, lines</td>
          <td>Java 11</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Files.readString, writeString</td>
          <td>Java 11</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>HttpClient</td>
          <td>Java 11</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Predicate.not()</td>
          <td>Java 11</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Single-file Programs (java Hello.java)</td>
          <td>Java 11</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Switch Expressions</td>
          <td>Java 12 (preview)</td>
          <td>Final in 14+</td>
          <td>Chapter 3</td>
        </tr>
        <tr>
          <td>String.indent, transform</td>
          <td>Java 12</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Text Blocks</td>
          <td>Java 13 (preview)</td>
          <td>Final in 15+</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Records</td>
          <td>Java 14 (preview)</td>
          <td>Final in 16+</td>
          <td>Chapter 5</td>
        </tr>
        <tr>
          <td>Pattern Matching for instanceof</td>
          <td>Java 14 (preview)</td>
          <td>Final in 16+</td>
          <td>Chapter 3</td>
        </tr>
        <tr>
          <td>Helpful NPE Messages</td>
          <td>Java 14</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Sealed Classes</td>
          <td>Java 15 (preview)</td>
          <td>Final in 17+</td>
          <td>Chapter 5</td>
        </tr>
        <tr>
          <td>String.formatted()</td>
          <td>Java 15</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Stream.toList()</td>
          <td>Java 16</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Stream.mapMulti()</td>
          <td>Java 16</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>RandomGenerator API</td>
          <td>Java 17</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Pattern Matching for switch</td>
          <td>Java 17 (preview)</td>
          <td>Final in 21+</td>
          <td>Chapter 3</td>
        </tr>
        <tr>
          <td>Virtual Threads</td>
          <td>Java 19 (preview)</td>
          <td>Final in 21+</td>
          <td>Chapter 9</td>
        </tr>
        <tr>
          <td>jwebserver (Simple Web Server)</td>
          <td>Java 18</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>@snippet in Javadoc</td>
          <td>Java 18</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>UTF-8 Default Charset</td>
          <td>Java 18</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Record Patterns</td>
          <td>Java 20 (preview)</td>
          <td>Final in 21+</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Sequenced Collections</td>
          <td>Java 21</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Unnamed Variables (_)</td>
          <td>Java 22</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Unnamed Classes and Instance main()</td>
          <td>Java 22 (preview)</td>
          <td>Final in 25+</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Foreign Function & Memory API</td>
          <td>Java 19 (preview)</td>
          <td>Final in 22+</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Stream.gather()</td>
          <td>Java 22 (preview)</td>
          <td>Final in 24+</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Markdown in Javadoc</td>
          <td>Java 23</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Primitive Patterns in switch</td>
          <td>Java 23</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Class-File API</td>
          <td>Java 24</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Flexible Constructor Bodies</td>
          <td>Java 25</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Module Import Declarations</td>
          <td>Java 25</td>
          <td>Final</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Value Classes</td>
          <td>Java 26 (preview)</td>
          <td>Preview</td>
          <td>Chapter 10</td>
        </tr>
        <tr>
          <td>Scoped Values</td>
          <td>Java 21 (preview)</td>
          <td>Final in 26</td>
          <td>Chapter 10</td>
        </tr>
      </table>` }} />
    ),
  },
  {
    id: 'summary',
    title: 'Key Takeaways',
    content: () => (
      <div dangerouslySetInnerHTML={{ __html: `<h2>Key Takeaways</h2>
      <ul>
        <li><strong>Java 9:</strong> Foundation for modular Java. Modules, immutable collections, and stream improvements make this a turning point.</li>
        <li><strong>Java 10-11:</strong> Ergonomic wins. var reduces boilerplate. HttpClient modernizes networking. String/Files APIs improve daily coding.</li>
        <li><strong>Java 12-17:</strong> Language evolution. Switch expressions, text blocks, records, sealed classes, and pattern matching transform how we write code.</li>
        <li><strong>Java 18-21 (LTS):</strong> Concurrency revolution. Virtual Threads reduce thread overhead from 1MB each to ~10KB. Transforms IO-bound applications.</li>
        <li><strong>Java 22-26:</strong> Continued refinement. Unnamed variables reduce noise. Unnamed classes simplify scripts. Value classes target performance (preview).</li>
        <li><strong>LTS Versions:</strong> Java 8, 11, 17, 21, 25. Use LTS for production. Non-LTS for experimentation.</li>
        <li><strong>Six-month release cycle:</strong> New version every 6 months. Features graduate from preview → final over multiple releases.</li>
      </ul>` }} />
    ),
  }
]
